# Change these first
owner: waspito
repo: waspito-status

assignees:
  - muarachmann
  
sites:
  - name: Waspito Platform
    url: https://waspito.com
  - name: Waspito Insurance
    url: https://insurance.waspito.com
  - name: Waspito Lab
    url: https://lab.waspito.com
 
status-website:
  favicon: https://www.waspito.com/favicon.ico
  faviconSvg: https://insurance.waspito.com/images/logo.svg
  cname: status.waspito.com
  logoUrl: https://insurance.waspito.com/images/logo.png
  name: Waspito
  introTitle: "**Waspito** is a telehealth app. We pull the whole healthcare ecosystem into one platform with objective to make basic healthcare more accessible and affordable."
  introMessage: We are the platform that engages Africa into the conversation and action to drive affordable and accessible quality healthcare across the continent.

  navbar:
    - title: Status
      href: /
    - title: Waspito
      href: https://waspito.com
    - title: Waspito
      href: https://insurance.waspito.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
